# Generated by Django 4.2.7 on 2023-11-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword_text', models.CharField(max_length=100)),
                ('is_soft_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('prompt_id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_text', models.CharField(max_length=500)),
                ('is_soft_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.keyword')),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.prompt')),
            ],
        ),
    ]
